version: '3'
services:
  # 指定服务名称
  shop-mysql:
    # 指定服务使用的镜像
    image: mysql:5.7
    # 指定容器名称
    container_name: shop-mysql
    # 指定服务运行的端口
    ports:
      - 3308:3306
    # 指定容器中需要挂载的文件
    volumes:
      - ./mydata/mysql/log:/var/log/mysql
      - ./mydata/mysql/data:/var/lib/mysql
      - ./mydata/mysql/conf:/etc/mysql
    # 指定容器的环境变量
    environment:
      - MYSQL_ROOT_PASSWORD=123456  
  
  # redis
  shop-redis:
    image: redis
    container_name: shop-redis
    command: redis-server --requirepass 123456
    ports:
      - 6379:6379 