version: '3'
services:
  shop-user-center:
    # 指定服务使用的镜像
    # image: shop-api
    # image: 192.168.10.240:8050/sym/shop-api
    build:
      context: .
      dockerfile: Dockerfile4UserCenter
    # 指定容器名称
    container_name: shop-user-center
    # 指定服务运行的端口
    ports:
      - 8081:9001
    external_links:
      - shop-mysql
      - consul4